#ifndef __KIWI_SYNTH_NOISE_H__
#define __KIWI_SYNTH_NOISE_H__


#include "daisysp.h"
#include "../Patch/PatchSettings.h"
#include "KiwiDust.h"

using namespace daisysp;

namespace kiwi_synth
{
    /*
     * The synth noise module.
     */
    class Noise
    {
        private:
            int        noiseType;
            float      level;
            float      lastSample;
            bool       isOn;
            bool       noteTriggered;
            WhiteNoise white;
            KiwiDust   dust;
            static constexpr float DEFAULT_DENSITY = 0.008f;

        public:
            Noise() {}
            ~Noise() {}
            void Init(float sampleRate);

            /*
             * Updates noise parameters based on user input.
             */
            void UpdateSettings(PatchSettings* patchSettings);

            /*
             * Generates noise. The value of the sample received as input will be ignored and overwritten.
             * This method also saves the last generated noise sample for the purpose of sample and hold
             * input.
             */
            inline void Process(float* sample, PatchSettings* patchSettings, float mod, float densityMod)
            {
                if (noiseType == 0) {
                    lastSample = white.Process() * 0.2;
                } else {
                    if (densityMod > 0.002f) {
                        dust.SetDensity(densityMod * densityMod * densityMod);
                    } else {
                        dust.SetDensity(DEFAULT_DENSITY);
                    }
                    lastSample = dust.Process();
                }

                if (isOn) {
                    *sample = lastSample * fclamp((level + mod), -1.0f, 1.0f);
                }
            }

            /*
             * Returns the last sample generated by the white noise module.
             */
            inline float GetLastSample() { return lastSample; }
    };
}


#endif // __KIWI_SYNTH_NOISE_H__
